// USERS
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const AUTHENTICATING_USER = 'AUTHENTICATING_USER';
export const AUTHENTICATED_USER = 'AUTHENTICATED_USER';
export const FAILED_LOGIN = 'FAILED_LOGIN';
export const LOGOUT = 'LOGOUT';
export const RESET_LOGIN_ERROR = 'RESET_LOGIN_ERROR';

// FAVORITE CAMPGROUNDS
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';
export const UPDATE_FAVORITE_FAIL = 'UPDATE_FAVORITE_FAIL';

// CAMPGROUNDS
export const UPDATE_SEARCHSTATE = 'UPDATE_SEARCHSTATE';
export const GET_CAMPGROUNDS = 'GET_CAMPGROUNDS';
export const GET_CAMPGROUNDS_START = 'GET_CAMPGROUNDS_START';
export const GET_CAMPGROUNDS_SUCCESS = 'GET_CAMPGROUNDS_SUCCESS';
export const GET_CAMPGROUNDS_FAIL = 'GET_CAMPGROUNDS_FAIL';
export const GET_CAMPGROUND = 'GET_CAMPGROUND';
export const GET_CAMPGROUND_START = 'GET_CAMPGROUND_START';
export const GET_CAMPGROUND_SUCCESS = 'GET_CAMPGROUND_SUCCESS';
export const GET_CAMPGROUND_FAIL = 'GET_CAMPGROUND_FAIL';
